[project]
name = "base-operators"
version = "0.2.0"
description = "A simple project to test cicd and github actions"
requires-python = ">=3.12"
dependencies = [
    "flake8>=7.1.1",
    "pytest>=8.3.3",
]
