[project]
name = "base-operators"
version = "0.3.3"
description = "A simple project to test cicd and github actions"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
    "ruff>=0.8.1",
]
