name: CI Pipeline

# Trigger this workflow on specific events
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest

      # Step 4: Run linting
      - name: Run flake8
        run: ruff check operators.py tests

      # Step 5: Run tests
      - name: Run pytest
        run: pytest
